services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80" # Map frontend to port 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000" # Map backend to port 5000
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306" # Maps the database to localhost
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro